export const inventoryConstants = {
  SET_INVENTORY: "SET_INVENTORY",
  SET_DEPARTMENT_FILTER: "SET_DEPARTMENT_FILTER",
  SET_LOW_STOCK_FILTER: "SET_LOW_STOCK_FILTER",
  SET_SORT_FILTER: "SET_SORT_FILTER",
};
